from datetime import datetime, date, time
from decimal import Decimal
from uuid import UUID
from typing import Any

class Field:
    def __get__(self, instance: object, owner: type) -> Any: ...
    def __set__(self, instance: object, value: Any) -> None: ...

class IntegerField(Field):
    def __get__(self, instance: object, owner: type) -> int: ...
    def __set__(self, instance: object, value: int) -> None: ...

class BigIntegerField(Field):
    def __get__(self, instance: object, owner: type) -> int: ...
    def __set__(self, instance: object, value: int) -> None: ...

class SmallIntegerField(Field):
    def __get__(self, instance: object, owner: type) -> int: ...
    def __set__(self, instance: object, value: int) -> None: ...

class FloatField(Field):
    def __get__(self, instance: object, owner: type) -> float: ...
    def __set__(self, instance: object, value: float) -> None: ...

class DoubleField(Field):
    def __get__(self, instance: object, owner: type) -> float: ...
    def __set__(self, instance: object, value: float) -> None: ...

class DecimalField(Field):
    def __get__(self, instance: object, owner: type) -> Decimal: ...
    def __set__(self, instance: object, value: Decimal) -> None: ...

class CharField(Field):
    def __get__(self, instance: object, owner: type) -> str: ...
    def __set__(self, instance: object, value: str) -> None: ...

class TextField(Field):
    def __get__(self, instance: object, owner: type) -> str: ...
    def __set__(self, instance: object, value: str) -> None: ...

class BooleanField(Field):
    def __get__(self, instance: object, owner: type) -> bool: ...
    def __set__(self, instance: object, value: bool) -> None: ...

class DateField(Field):
    def __get__(self, instance: object, owner: type) -> date: ...
    def __set__(self, instance: object, value: date) -> None: ...

class TimeField(Field):
    def __get__(self, instance: object, owner: type) -> time: ...
    def __set__(self, instance: object, value: time) -> None: ...

class DateTimeField(Field):
    def __get__(self, instance: object, owner: type) -> datetime: ...
    def __set__(self, instance: object, value: datetime) -> None: ...

class UUIDField(Field):
    def __get__(self, instance: object, owner: type) -> UUID: ...
    def __set__(self, instance: object, value: UUID) -> None: ...

class ForeignKeyField(Field):
    def __get__(self, instance: object, owner: type) -> Any: ...
    def __set__(self, instance: object, value: Any) -> None: ...
